name: "Aspect Lua Template"
description: "Aspect is a compiling template engine for Lua and LuaJIT(OpenResty, Tarantool) with syntax Twig/Jinja/Django/Liquid."
destination: ./build
encoding: UTF-8
markdown: kramdown
url: "https://unifire-app.github.io/"